services:
    web:
        image: nginx
        container_name: sio_web
        volumes:
            - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "${PROJECT_PORT}:80"
        restart: always
        depends_on:
            - php-fpm
            - db
    php-fpm:
        build: docker
        container_name: sio_app
        restart: always
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
        env_file:
            - .env

    db:
        image: postgres:15-alpine
        container_name: sio_db
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/postgres/pgdata:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"